/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.limsi.wapiti;

public class WapitiJNI {
  public final static native void delete_WapitiIO(long jarg1);
  public final static native String WapitiIO_readline(long jarg1, WapitiIO jarg1_);
  public final static native String WapitiIO_readlineSwigExplicitWapitiIO(long jarg1, WapitiIO jarg1_);
  public final static native void WapitiIO_append(long jarg1, WapitiIO jarg1_, String jarg2);
  public final static native void WapitiIO_appendSwigExplicitWapitiIO(long jarg1, WapitiIO jarg1_, String jarg2);
  public final static native long new_WapitiIO();
  public final static native void WapitiIO_director_connect(WapitiIO obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void WapitiIO_change_ownership(WapitiIO obj, long cptr, boolean take_or_release);
  public final static native String wapiti_gets_cb(long jarg1);
  public final static native int wapiti_print_cb(long jarg1, String jarg2);
  public final static native long new_WapitiModel(long jarg1, WapitiIO jarg1_);
  public final static native void delete_WapitiModel(long jarg1);
  public final static native void WapitiModel_label(long jarg1, WapitiModel jarg1_, long jarg2, WapitiIO jarg2_);

  public static String SwigDirector_WapitiIO_readline(WapitiIO jself) {
    return jself.readline();
  }
  public static void SwigDirector_WapitiIO_append(WapitiIO jself, String data) {
    jself.append(data);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
