/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.limsi.wapiti;

public class Wapiti {
  public static String wapiti_gets_cb(SWIGTYPE_p_void x) {
    return WapitiJNI.wapiti_gets_cb(SWIGTYPE_p_void.getCPtr(x));
  }

  public static int wapiti_print_cb(SWIGTYPE_p_void x, String format) {
    return WapitiJNI.wapiti_print_cb(SWIGTYPE_p_void.getCPtr(x), format);
  }

}
