/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.limsi.wapiti;

public class WapitiModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WapitiModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WapitiModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WapitiJNI.delete_WapitiModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WapitiModel(WapitiIO io) {
    this(WapitiJNI.new_WapitiModel(WapitiIO.getCPtr(io), io), true);
  }

  public void label(WapitiIO io) {
    WapitiJNI.WapitiModel_label(swigCPtr, this, WapitiIO.getCPtr(io), io);
  }

}
